import mongoose from "mongoose";

const productSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true
    },
    description:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true,
        min:0
    },
    discountPrice:{
        type:Number
    },
    countInStock:{
        type:Number,
        default:true,
        default:0
    },
    sku:{
        type:String,
        required:true,
        unique:true
    },
    category:{
        type:String,
        required:true
    },
    brand:{
        type:String,
    },
    sizes:{
        type:[String],
        required:true
    },
    color:{
        type:[String],
        required:true
    },
    collections:{
        type:String,
        required:true
    },
    material:{
        type:String,
    },
    gender:{
        type:String,
        enum:["male","Female","Unisex"]
    },
    images:[
        {
            url:{
                type:String,
                required:true
            },
            altText:{
                type:String,
                required:true
            }
        }
    ],
    isFeatured:{
        type:Boolean,
        default:false
    },
    isPublished:{
        type:Boolean,
        default:false
    },
    ratting:{
        type:Number,
        default:0
    },
    numReviews:{
        type:Number,
        default:0
    },
    tags:[String],
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    metaTitle:{
        type:String
    },
    metaDescription:{
        type:String,
    },metaKeywords:{
        type:String,
    },
    dimension:{
        length:Number,
        width:Number,
        height:Number
    },
    weight:Number
},{timestamps:true})

const Product = mongoose.model("Product",productSchema)
export default Product